import { describe, it, expect } from 'vitest';
import { Schema as S } from 'effect';
import { generateViews, resolveVisibleFields } from './codegen';
import { ui, extractBlueprint } from './annotation';
import { DEFAULT_SLOT_MAP } from './slot-map';

// Test blueprint
const IssueSchema = S.Struct({
  id: S.String.pipe(ui('identifier', 1, { label: 'ID' })),
  title: S.String.pipe(ui('title', 2, { label: 'Title' })),
  status: S.Literal('open', 'closed').pipe(ui('status', 3, { label: 'Status' })),
  body: S.String.pipe(ui('content', 5, { label: 'Body' })),
  count: S.Number.pipe(ui('metric', 4, { label: 'Comments' })),
});

describe('resolveVisibleFields', () => {
  const fields = extractBlueprint(IssueSchema);

  it('card: shows title, status, metric, content excerpt — hides identifier', () => {
    const visible = resolveVisibleFields(fields, 'card');
    const names = visible.map(f => f.name);
    expect(names).toContain('title');
    expect(names).toContain('status');
    expect(names).toContain('count');
    expect(names).toContain('body'); // content → card-excerpt
    expect(names).not.toContain('id'); // identifier → hidden in card
  });

  it('row: shows id, title, status, metric — hides content', () => {
    const visible = resolveVisibleFields(fields, 'row');
    const names = visible.map(f => f.name);
    expect(names).toContain('id');
    expect(names).toContain('title');
    expect(names).toContain('status');
    expect(names).toContain('count');
    expect(names).not.toContain('body'); // content → hidden in row
  });

  it('detail: shows all fields', () => {
    const visible = resolveVisibleFields(fields, 'detail');
    expect(visible).toHaveLength(5);
  });

  it('pin: shows only title and metric', () => {
    const visible = resolveVisibleFields(fields, 'pin');
    const names = visible.map(f => f.name);
    // title → tooltip, metric → pin-label, status → pin-color
    // identifier → hidden, content → hidden
    expect(visible.length).toBeLessThanOrEqual(3);
  });

  it('resolves correct slot for each field', () => {
    const visible = resolveVisibleFields(fields, 'card');
    const titleField = visible.find(f => f.name === 'title');
    expect(titleField?.slot).toBe('card-title');

    const statusField = visible.find(f => f.name === 'status');
    expect(statusField?.slot).toBe('card-badge');
  });
});

describe('generateViews', () => {
  it('generates views for specified shapes', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card', 'row'],
    });
    expect(result.views).toHaveLength(2);
    expect(result.views[0].componentName).toBe('IssueCard');
    expect(result.views[1].componentName).toBe('IssueRow');
  });

  it('generates correct component name for compound shapes', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['compact-card'],
    });
    expect(result.views[0].componentName).toBe('IssueCompactCard');
  });

  it('generated source contains component function', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    const cardView = result.views[0];
    expect(cardView.source).toContain('export const IssueCard');
    expect(cardView.source).toContain('IssueCardOverrides');
    expect(cardView.source).toContain('IssueCardSkeleton');
  });

  it('generated source contains slot data attributes', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    expect(result.views[0].source).toContain('data-slot="card-title"');
    expect(result.views[0].source).toContain('data-slot="card-badge"');
  });

  it('generated source contains field data attributes', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    expect(result.views[0].source).toContain('data-field="title"');
    expect(result.views[0].source).toContain('data-field="status"');
  });

  it('generated source has auto-generated header', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    expect(result.fileSource).toContain('Auto-generated by @ybouhjira/hyperkit-views');
    expect(result.fileSource).toContain('DO NOT EDIT');
  });

  it('fileSource contains all views', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card', 'row', 'detail'],
    });
    expect(result.fileSource).toContain('IssueCard');
    expect(result.fileSource).toContain('IssueRow');
    expect(result.fileSource).toContain('IssueDetail');
  });

  it('overrides interface lists visible fields', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    const source = result.views[0].source;
    expect(source).toContain('export interface IssueCardOverrides');
    expect(source).toContain('title?:');
    expect(source).toContain('status?:');
  });

  it('skeleton component is generated', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    expect(result.views[0].source).toContain('IssueCardSkeleton');
    expect(result.views[0].source).toContain('sk-view-skeleton');
    expect(result.views[0].source).toContain('sk-skeleton-slot');
  });

  it('visible fields exclude hidden slots', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
    });
    const cardView = result.views[0];
    const fieldNames = cardView.visibleFields.map(f => f.name);
    // identifier is hidden in card view
    expect(fieldNames).not.toContain('id');
  });

  it('accepts custom slot map', () => {
    const result = generateViews(IssueSchema, {
      name: 'Issue',
      shapes: ['card'],
      slotMap: {
        ...DEFAULT_SLOT_MAP,
        identifier: { ...DEFAULT_SLOT_MAP.identifier, card: 'card-subtitle' },
      },
    });
    const cardView = result.views[0];
    const fieldNames = cardView.visibleFields.map(f => f.name);
    // Now identifier IS visible in card
    expect(fieldNames).toContain('id');
  });
});
