import { render } from '@solidjs/testing-library';
import { describe, it, expect } from 'vitest';
import { ReportFooter } from './ReportFooter';

describe('ReportFooter', () => {
  it('renders footer text', () => {
    const { getByText } = render(() => <ReportFooter text="Generated by SolidKit v2.5.0" />);
    expect(getByText('Generated by SolidKit v2.5.0')).toBeInTheDocument();
  });

  it('renders as a footer element', () => {
    const { container } = render(() => <ReportFooter text="Footer" />);
    const footer = container.querySelector('footer');
    expect(footer).toBeInTheDocument();
    expect(footer?.classList.contains('sk-report-footer')).toBe(true);
  });

  it('renders empty text', () => {
    const { container } = render(() => <ReportFooter text="" />);
    const footer = container.querySelector('footer');
    expect(footer).toBeInTheDocument();
    expect(footer?.textContent).toBe('');
  });

  it('renders long text content', () => {
    const longText = 'Copyright 2026 SolidKit. All rights reserved. Built with SolidJS.';
    const { getByText } = render(() => <ReportFooter text={longText} />);
    expect(getByText(longText)).toBeInTheDocument();
  });

  it('renders text with special characters', () => {
    const { getByText } = render(() => <ReportFooter text="v2.5.0 — MIT License" />);
    expect(getByText('v2.5.0 — MIT License')).toBeInTheDocument();
  });
});
