import { IssueBoard } from '@ybouhjira/hyperkit'
import type { Issue } from '@ybouhjira/hyperkit'
import { defineStory, control } from '../src/api'

const mockIssues: Issue[] = [
  {
    id: '1',
    number: 123,
    title: 'Add dark mode support to all components',
    body: 'All components should support dark mode via CSS variables',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'P1', color: 'f97316' },
      { name: 'good first issue', color: '7057ff' },
    ],
    assignee: 'youssef',
    milestone: 'v3.0.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/123',
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-03-07T15:30:00Z',
    priority: 'P1',
  },
  {
    id: '2',
    number: 124,
    title: 'Fix button hover state in Safari',
    body: 'Button component has broken hover state in Safari 17+',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'P0', color: 'ef4444' },
    ],
    assignee: null,
    milestone: 'v2.6.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/124',
    createdAt: '2026-03-05T09:00:00Z',
    updatedAt: '2026-03-08T08:00:00Z',
    priority: 'P0',
  },
  {
    id: '3',
    number: 45,
    title: 'Add invoice generation feature',
    body: 'Generate PDF invoices from order data',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'P2', color: 'eab308' },
    ],
    assignee: 'alice',
    milestone: 'Q2 2026',
    repo: 'ybouhjira/phoenix-erp',
    url: 'https://github.com/ybouhjira/phoenix-erp/issues/45',
    createdAt: '2026-02-20T14:00:00Z',
    updatedAt: '2026-03-06T10:00:00Z',
    priority: 'P2',
  },
  {
    id: '4',
    number: 46,
    title: 'Database migration fails on PostgreSQL 15',
    body: 'Migration script throws syntax error on PostgreSQL 15',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'P1', color: 'f97316' },
      { name: 'database', color: '0e8a16' },
    ],
    assignee: 'bob',
    milestone: null,
    repo: 'ybouhjira/phoenix-erp',
    url: 'https://github.com/ybouhjira/phoenix-erp/issues/46',
    createdAt: '2026-03-03T11:00:00Z',
    updatedAt: '2026-03-07T16:00:00Z',
    priority: 'P1',
  },
  {
    id: '5',
    number: 12,
    title: 'Support UML class diagram import from PlantUML',
    body: 'Add PlantUML parser to import class diagrams',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'P3', color: '3b82f6' },
    ],
    assignee: null,
    milestone: 'v2.0.0',
    repo: 'ybouhjira/uml-viewer',
    url: 'https://github.com/ybouhjira/uml-viewer/issues/12',
    createdAt: '2026-02-15T13:00:00Z',
    updatedAt: '2026-03-04T09:00:00Z',
    priority: 'P3',
  },
  {
    id: '6',
    number: 13,
    title: 'Diagram export to SVG broken',
    body: 'SVG export produces invalid markup',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'P0', color: 'ef4444' },
    ],
    assignee: 'charlie',
    milestone: 'v1.5.1',
    repo: 'ybouhjira/uml-viewer',
    url: 'https://github.com/ybouhjira/uml-viewer/issues/13',
    createdAt: '2026-03-07T08:00:00Z',
    updatedAt: '2026-03-08T07:00:00Z',
    priority: 'P0',
  },
  {
    id: '7',
    number: 125,
    title: 'Update documentation for theming API',
    body: 'Documentation is outdated for new theming system',
    state: 'open',
    labels: [
      { name: 'documentation', color: '0075ca' },
      { name: 'P2', color: 'eab308' },
    ],
    assignee: null,
    milestone: null,
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/125',
    createdAt: '2026-03-02T16:00:00Z',
    updatedAt: '2026-03-05T14:00:00Z',
    priority: 'P2',
  },
  {
    id: '8',
    number: 126,
    title: 'Add accessibility tests',
    body: 'Add automated accessibility tests for all components',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'accessibility', color: 'f9d0c4' },
      { name: 'P1', color: 'f97316' },
    ],
    assignee: 'youssef',
    milestone: 'v3.0.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/126',
    createdAt: '2026-02-28T12:00:00Z',
    updatedAt: '2026-03-06T11:00:00Z',
    priority: 'P1',
  },
  {
    id: '9',
    number: 47,
    title: 'Inventory sync with warehouse system',
    body: 'Real-time sync with external warehouse management system',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'integration', color: 'fbca04' },
      { name: 'P3', color: '3b82f6' },
    ],
    assignee: 'alice',
    milestone: 'Q3 2026',
    repo: 'ybouhjira/phoenix-erp',
    url: 'https://github.com/ybouhjira/phoenix-erp/issues/47',
    createdAt: '2026-02-25T10:00:00Z',
    updatedAt: '2026-03-03T15:00:00Z',
    priority: 'P3',
  },
  {
    id: '10',
    number: 48,
    title: 'Login page timeout too short',
    body: 'Users complain about session timeout being too aggressive',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'P2', color: 'eab308' },
      { name: 'ux', color: 'c5def5' },
    ],
    assignee: null,
    milestone: 'Q2 2026',
    repo: 'ybouhjira/phoenix-erp',
    url: 'https://github.com/ybouhjira/phoenix-erp/issues/48',
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-03-07T12:00:00Z',
    priority: 'P2',
  },
  {
    id: '11',
    number: 14,
    title: 'Add sequence diagram support',
    body: 'Implement sequence diagram rendering',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'P1', color: 'f97316' },
    ],
    assignee: 'charlie',
    milestone: 'v2.0.0',
    repo: 'ybouhjira/uml-viewer',
    url: 'https://github.com/ybouhjira/uml-viewer/issues/14',
    createdAt: '2026-02-18T14:00:00Z',
    updatedAt: '2026-03-05T10:00:00Z',
    priority: 'P1',
  },
  {
    id: '12',
    number: 127,
    title: 'Performance regression in Table component',
    body: 'Table component is slow with 1000+ rows',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'performance', color: 'ee0701' },
      { name: 'P0', color: 'ef4444' },
    ],
    assignee: 'youssef',
    milestone: 'v2.6.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/127',
    createdAt: '2026-03-06T10:00:00Z',
    updatedAt: '2026-03-08T09:00:00Z',
    priority: 'P0',
  },
  {
    id: '13',
    number: 128,
    title: 'Add Dropdown component',
    body: 'Implement accessible dropdown menu component',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'good first issue', color: '7057ff' },
      { name: 'P3', color: '3b82f6' },
    ],
    assignee: null,
    milestone: 'v3.0.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/128',
    createdAt: '2026-02-22T11:00:00Z',
    updatedAt: '2026-03-02T16:00:00Z',
    priority: 'P3',
  },
  {
    id: '14',
    number: 49,
    title: 'Add multi-currency support',
    body: 'Support multiple currencies in accounting module',
    state: 'closed',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'P1', color: 'f97316' },
    ],
    assignee: 'bob',
    milestone: 'Q1 2026',
    repo: 'ybouhjira/phoenix-erp',
    url: 'https://github.com/ybouhjira/phoenix-erp/issues/49',
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-28T14:00:00Z',
    priority: 'P1',
  },
  {
    id: '15',
    number: 15,
    title: 'Zoom controls not working in Firefox',
    body: 'Diagram zoom buttons have no effect in Firefox',
    state: 'open',
    labels: [
      { name: 'bug', color: 'd73a4a' },
      { name: 'P2', color: 'eab308' },
    ],
    assignee: null,
    milestone: 'v1.5.1',
    repo: 'ybouhjira/uml-viewer',
    url: 'https://github.com/ybouhjira/uml-viewer/issues/15',
    createdAt: '2026-03-04T13:00:00Z',
    updatedAt: '2026-03-07T11:00:00Z',
    priority: 'P2',
  },
  {
    id: '16',
    number: 129,
    title: 'Add Modal component animation',
    body: 'Add enter/exit animations to Modal component',
    state: 'open',
    labels: [
      { name: 'enhancement', color: 'a2eeef' },
      { name: 'ux', color: 'c5def5' },
      { name: 'P2', color: 'eab308' },
    ],
    assignee: 'youssef',
    milestone: 'v2.6.0',
    repo: 'ybouhjira/hyperkit',
    url: 'https://github.com/ybouhjira/hyperkit/issues/129',
    createdAt: '2026-03-03T15:00:00Z',
    updatedAt: '2026-03-07T09:00:00Z',
    priority: 'P2',
  },
]

const repos = ['ybouhjira/hyperkit', 'ybouhjira/phoenix-erp', 'ybouhjira/uml-viewer']

export default defineStory({
  title: 'Composites/IssueBoard',
  component: IssueBoard,
  controls: {
    view: control.select(['list', 'board', 'table'], 'list', 'View'),
    groupBy: control.select(['none', 'repo', 'priority', 'label', 'milestone'], 'none', 'Group By'),
    state: control.select(['open', 'closed', 'all'], 'open', 'State Filter'),
  },
  render: (controls) => {
    return (
      <div style={{ height: '800px', width: '100%' }}>
        <IssueBoard
          issues={mockIssues}
          repos={repos}
          view={controls.view}
          groupBy={controls.groupBy}
          filters={{ state: controls.state }}
          onIssueClick={(issue) => console.log('Issue clicked:', issue)}
          onStartWork={(issue) => console.log('Start work on:', issue)}
        />
      </div>
    )
  },
})
