/* eslint-disable no-console */
import * as fs from 'fs';
import * as path from 'path';

export function themeGenerate(options: { input: string; output: string }) {
  const inputPath = path.resolve(options.input);
  const outputPath = path.resolve(options.output);

  if (!fs.existsSync(inputPath)) {
    console.error(`❌ Theme file not found: ${inputPath}`);
    console.log('  Run "hyperkit init" first to create a theme file.');
    process.exit(1);
  }

  // Read and parse the theme file to extract custom property keys
  const content = fs.readFileSync(inputPath, 'utf-8');

  // Extract customProperties keys if present
  const customPropsMatch = content.match(/customProperties\s*:\s*\{([^}]+)\}/);
  const customKeys: string[] = [];

  if (customPropsMatch) {
    const propsContent = customPropsMatch[1];
    const keyMatches = propsContent.matchAll(/['"]?(\w[\w-]*)['"]?\s*:/g);
    for (const match of keyMatches) {
      customKeys.push(match[1]);
    }
  }

  // Generate declaration file
  let output = `// Auto-generated by hyperkit CLI\n`;
  output += `// Do not edit manually - run "hyperkit theme generate" to regenerate\n\n`;

  if (customKeys.length > 0) {
    output += `declare module '@ybouhjira/hyperkit' {\n`;
    output += `  interface CustomThemeProperties {\n`;
    for (const key of customKeys) {
      output += `    '${key}': string;\n`;
    }
    output += `  }\n`;
    output += `}\n\n`;
  }

  output += `export {};\n`;

  fs.writeFileSync(outputPath, output, 'utf-8');
  console.log(`✅ Generated ${path.relative(process.cwd(), outputPath)}`);
  if (customKeys.length > 0) {
    console.log(`   ${customKeys.length} custom properties typed`);
  }
}
