import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ filesystem:
 * - Top-level sections are ordered by their _category_.json `position`.
 * - Pages are ordered by `sidebar_position` front matter.
 * - Component pages under docs/components/ are generated by
 *   scripts/generate-component-docs.mjs from ../docs-manifest.json.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
